[db]
host = 192.168.1.100
port = 3306
user = root
pwd = qwer1234
database = StudentV4DB
charset = utf8
newkey = newValue

[test_data]
phone = YOUR_PHONE
pwd = 12345678

[case]
testcase = test_jyjApi.xlsx

[identifier]
note = #

[log]
level = DEBUG
#DEBUG INFO WARN ERROR FATAL   logging五个等等级

[email]
host = smtp.qq.com
port = 465
user = 216***145@qq.com
pwd = pof*****djbh
from_addr = 21647**6145@qq.com
to_addr = 5***3756@qq.com


[wechat]
corpid = wwb7******41c0e
corpsecret = oo6E*****************glmHpcOMo
agentid = 10*****2


[par]
phone = YOUR_PHONE
pwd = 123456



[commkey]
获取当前执行用例 = get_exceut_case
获取当前用例文件名称 = get_current_casefile_name
post = send_api
get = send_api
发送消息 = send_msg
字典取值 = get_json_value_as_key
设置变量 = set_variable
执行SQL = execut_sql
发送邮件 = send_email