[Urls]
ip =192.168.1.100
#设备IP

video_url = https://b23.tv/lM1gAd9
#B站视频播放网址

web_url = https://m.ithome.com
#IT之家首页

[Settings]
game_name = 崩铁
#填原神或崩铁

video_time = 1
#视频播放时长，单位为分钟

game_time = 1
#游戏运行时长，单位为分钟

web_time = 1 
#IT之家浏览时长，单位为分钟

test_times = 2
#运行的次数，想运行到没电需要填多一点次数