[device_info]
;设备远程链接URL 设备ip+端口或者设备唯一标识id
device = 192.168.1.100:5555
platform = Android

[paths]
;自定义执行case目录层级，文件夹名称（例如：suits），默认为空
name = all_suit

[report_name]
;自定义执行报告名称(自定义名称，不需要加html后缀)
report_name = ywtest

[reboot]
;在运行用例前选择是否先重启机器（填True或False）
is_reboot = True

[reboot_num]
;每运行多少条用例后重启机器（填数字），由于一直不重启机器会导致机器内存溢出而卡死，此处填25以下均可
reboot_num = 5

[global_settings]
;全局的变量的设置
;THRESHOLD表示图片的相似阈值，如果用例里写了，以用例里为准，没写自动带入全局设置值
;IMAGE_MAXSIZE表示截图时的图像大小，此处填最长的边的值，如需要设置7680*4320的截图大小，则填写7680
;SAVE_IMAGE表示运行用例时是否进行截图
THRESHOLD = 0.85
IMAGE_MAXSIZE = 7680
SAVE_IMAGE = True

[suit_select]
;选择运行的用例,目前可选【国内、海外】，可根据自己的环境进行选择，部分用例有差异，会根据选择的标签运行相应的用例
suit_select = 国内

[run_times]
;选择重复运行的次数，0表示不重复运行;1表示重复运行一次，总共运行2次
run_times = 100